# Generated by Django 3.1.7 on 2021-03-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='a_host_name', max_length=50),
        ),
    ]
