# Generated by Django 3.1.7 on 2021-03-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20210316_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
    ]
